export const data_tab4_faseB = [
  {
    id: 1,
    Cliente: "FUJIOKA",
    NAM: "LUCIA",
    MANAGER: "ANDREYA",
    Part_Number: "910-005235",
    MKT_Name: "Receptor USB Logitech Unifying  ",
    Runrate_NPI: "RUNRATE",
    Product_Group: "Pointing Devices Group",
    CHAVE: "FUJIOKA910-005235",
    Q1_NAM_Total_estoque_cliente_PÇS_: "0.0",
    Q1_NAM_Estoque_Projetado: "0",
    Q1_NAM_Estoque_Ajustado: "0.0",
    Q1_NAM_WOH: null,
    Q1_Abril: "0.0",
    Q1_Maio: "0.0",
    Q1_Junho: "0.0",
    Q1_Forecast_Q1: "0.0",
    Q1_Total_Q1_ano_anterior: "0.0",
    Q1_Forecast_Q1_Evento_Q1: "0.0",
    Q1_Variação_YoY: "0%",
    Q2_Estoque_Projetado: "0",
    Q2_WOH: null,
    Q2_Julho: "0.0",
    Q2_Agosto: "0.0",
    Q2_Setembro: "0.0",
    Q2_Forecast_Q2: "0.0",
    Q2_Total_Q2_ano_anterior: "0.0",
    Q2_Forecast_Q2_Evento_Q2: "0.0",
    Q2_Variação_YoY: "0%",
    Q3_Estoque_Projetado: "0",
    Q3_WOH: null,
    Q3_Outubro: "0.0",
    Q3_Novembro: "0.0",
    Q3_Dezembro: "0.0",
    Q3_Forecast_Q3: "0.0",
    Q3_Total_Q3_ano_anterior: "0.0",
    Q3_Forecast_Q3_Evento_Q3: "0.0",
    Q3_Variação_YoY: "0%",
    Q4_Estoque_Projetado: "0",
    Q4_WOH: null,
    Q4_Janeiro: "0.0",
    Q4_Fevereiro: "0.0",
    Q4_Março: "0.0",
    Q4_Forecast_Q4: "0.0",
    Q4_Total_Q4_ano_anterior: "0.0",
    Q4_Forecast_Q4_Evento_Q4: "0.0",
    Q4_Variação_YoY: "0%",
  },
];
