// data.js
// Dados de exemplo para ForecastDataGrid.
// Contém 12 linhas com 10 colunas cada, correspondentes às seguintes colunas:
// Cliente T2, Vendedor, Gerente, Categoria Produto, Subcategoria, Cód Produto,
// Descrição Produto, Tipo fcst (lçto/venda corrente), Valor R$, Valor BRL

export const initialData = [
  {
    id: 1,
    cliente_t2: "Cliente 1",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 2,
    cliente_t2: "Cliente 1",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
  {
    id: 3,
    cliente_t2: "Cliente 2",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 4,
    cliente_t2: "Cliente 2",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
  {
    id: 5,
    cliente_t2: "Cliente 3",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 6,
    cliente_t2: "Cliente 3",
    vendedor: "Alex",
    gerente: "Ana",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
  {
    id: 7,
    cliente_t2: "Cliente 4",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 8,
    cliente_t2: "Cliente 4",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
  {
    id: 9,
    cliente_t2: "Cliente 5",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 10,
    cliente_t2: "Cliente 5",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
  {
    id: 11,
    cliente_t2: "Cliente 6",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM1-TRADICIONAL",
    descricao_produto: "Amaciante 2L Tradicional",
    tipo_fcst: "Venda corrente",
    valor: 3.33333333333333,
    valor_brl: 20,
  },
  {
    id: 12,
    cliente_t2: "Cliente 6",
    vendedor: "Fabio",
    gerente: "Eliane",
    categoria_produto: "Lava Roupas",
    subcategoria: "Amaciante",
    cod_produto: "AM2-LAVANDA",
    descricao_produto: "Amaciante 2L Lavanda",
    tipo_fcst: "Venda corrente",
    valor: 4.16666666666667,
    valor_brl: 25,
  },
];
